"""Enhance user and profile tables

Revision ID: 2a191fdd6298
Revises: 75f2c0a7dbc5
Create Date: 2026-05-02 20:15:27.144340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a191fdd6298'
down_revision = '75f2c0a7dbc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('card_number', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('card_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('card_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dr_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('floor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=True))
        batch_op.drop_column('address')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), server_default=sa.false(), nullable=False))

    op.execute("UPDATE users SET username = 'user_' || id WHERE username IS NULL")
    op.execute("UPDATE users SET account_number = '7' || lpad(id::text, 9, '0') WHERE account_number IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)
        batch_op.alter_column('account_number', nullable=False)
        batch_op.alter_column('is_premium', server_default=None)
        batch_op.create_index(batch_op.f('ix_users_account_number'), ['account_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_account_number'))
        batch_op.drop_column('is_premium')
        batch_op.drop_column('account_number')
        batch_op.drop_column('username')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('area')
        batch_op.drop_column('street')
        batch_op.drop_column('floor')
        batch_op.drop_column('dr_no')
        batch_op.drop_column('card_type')
        batch_op.drop_column('card_name')
        batch_op.drop_column('card_number')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
